add import function and code reformat

diff --git a/github-tools-includes b/github-tools-includes
--- a/github-tools-includes
+++ b/github-tools-includes
@@ -33,211 +33,249 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
-export GHTOOLS_VERSION="1.2.1"
+export GHTOOLS_VERSION="1.3.0"
 export GHTOOLS_DEBUG=
 export GHTOOLS_ROOT=
 
 gh_help () {
-  cat << END-OF-USAGE-TEXT
-USAGE: ght command [params]
+	cat <<- END-OF-USAGE-TEXT
+		USAGE: ght command [params]
 
-commands:
+		commands:
 
-help                   ... displays this page
-version                ... displays version info
-clone <repo> [user-id] ... clones a repository 
-info  [user-id]        ... returns account informations in json format 
-repos [user-id]        ... returns list of repository names 
-repos-urls [user-id]   ... returns list of repository urls
-repos-json [user-id]   ... returns repos informations in json format
-backup [user-id]       ... loop through all repos of a user account and either
-                           clones them or uses 'git pull' to update them.
-root [abspath]         ... set prefix for command go
-go <relpath>           ... changes to dir <root>/<relpath> if root is set 
-debug [on]             ... enables/disables debug (without parameter == off]
+		help                   ... displays this page
+		version                ... displays version info
+		clone <repo>           ... clones a repository 
+		info  [user-id]        ... returns account informations in json format
+		repos [user-id]        ... returns list of repository names
+		repos-urls [user-id]   ... returns list of repository urls
+		repos-json [user-id]   ... returns repos informations in json format
+		backup [user-id]       ... loop through all repos of a user account and
+		                           either clones them or uses 'git pull'.
+		root [abspath]         ... set prefix for command go
+		go <relpath>           ... changes to dir <root>/<relpath> if root is set
+		debug [on]             ... enables/disables debug
+		                           (without parameter == off]
+		import [user-id]       ... imports current git repo to github (note: the
+		                           user-id is derived from parent dir)
 
-If you omit the optional parameter user-id, the name of the active working 
-directory will be used as github user-id.
-END-OF-USAGE-TEXT
+
+		If you omit the optional parameter user-id, the name of the active
+		working directory will be used as github user-id.
+	END-OF-USAGE-TEXT
 }
 
 __gh_debug () {
-  [ -n "$GHTOOLS_DEBUG" ] && printf '[DEBUG] %s\n' "$*" 1>&2
+	[ -n "$GHTOOLS_DEBUG" ] && printf >&2 '[DEBUG] %s\n' "$*"
 }
 
-__gh_error () {
-  printf '[ERROR] %s\n' "$*" 1>&2
-}
-
-__gh_info () {
-  printf '[INFO] %s\n' "$*"
-}
-
-__gh_warn () {
-  printf '[WARNING] %s\n' "$*" 1>&2
-}
+__gh_error () { printf >&2 '[ERROR] %s\n' "$*"; }
+__gh_warn ()  { printf >&2 '[WARNING] %s\n' "$*"; }
+__gh_info ()  { printf '[INFO] %s\n' "$*"; }
 
 __gh_rm_path () {
-  echo "$*" | sed 's/.*\/\(.*\)$/\1/g'
+	echo "$1" | sed 's/.*\/\(.*\)$/\1/g'
 }
 
 __gh_local_dir () {
-  __gh_rm_path $(pwd)
-} 
+	__gh_rm_path $(pwd)
+}
+
+__gh_parent_dir () {
+	cd .. >&2 2>/dev/null
+	__gh_rm_path $(pwd)
+	cd - >&2 2>/dev/null
+}
 
 ## that one is a bitch ...
 __gh_url_encode() {
-  export LANG=C  
-  __gh_debug "encoding [$*]"
-  echo "$@" | awk '
-    BEGIN {
-    # We assume an awk implementation that is just plain dumb.
-    # We will convert an character to its ASCII value with the
-    # table ord[], and produce two-digit hexadecimal output
-    # without the printf("%02X") feature.
+	export LANG=C
+	__gh_debug "encoding [$*]"
+	echo "$@" | awk '
+		BEGIN {
+			# We assume an awk implementation that is just plain dumb.
+			# We will convert an character to its ASCII value with the
+			# table ord[], and produce two-digit hexadecimal output
+			# without the printf("%02X") feature.
 
-    EOL = "%0A"     # "end of line" string (encoded)
-    split ("1 2 3 4 5 6 7 8 9 A B C D E F", hextab, " ")
-    hextab [0] = 0
-    for ( i=1; i<=255; ++i ) ord [ sprintf ("%c", i) "" ] = i + 0
-    EncodeEOL = 0; # no end-of-line encoding for now
-    }
-    {
-    encoded = ""
-    for ( i=1; i<=length ($0); ++i ) {
-        c = substr ($0, i, 1)
-        if ( c ~ /[a-zA-Z0-9.-]/ ) {
-        encoded = encoded c     # safe character
-        } else if ( c == " " ) {
-        encoded = encoded "+"   # special handling
-        } else {
-        # unsafe character, encode it as a two-digit hex-number
-        lo = ord [c] % 16
-        hi = int (ord [c] / 16);
-        encoded = encoded "%" hextab [hi] hextab [lo]
-        }
-    }
-    if ( EncodeEOL ) {
-        printf ("%s", encoded EOL)
-    } else {
-        print encoded
-    }
-    }
-    END {
-        #if ( EncodeEOL ) print ""
-    }
-  '
+			EOL = "%0A"     # "end of line" string (encoded)
+			split ("1 2 3 4 5 6 7 8 9 A B C D E F", hextab, " ")
+			hextab [0] = 0
+			for ( i=1; i<=255; ++i ) ord [ sprintf ("%c", i) "" ] = i + 0
+			EncodeEOL = 0; # no end-of-line encoding for now
+		}
+		{
+			encoded = ""
+			for ( i=1; i<=length ($0); ++i ) {
+				c = substr ($0, i, 1)
+				if ( c ~ /[a-zA-Z0-9.-]/ ) {
+					encoded = encoded c     # safe character
+				} else if ( c == " " ) {
+					encoded = encoded "+"   # special handling
+				} else {
+					# unsafe character, encode it as a two-digit hex-number
+					lo = ord [c] % 16
+					hi = int (ord [c] / 16);
+					encoded = encoded "%" hextab [hi] hextab [lo]
+				}
+			}
+			if ( EncodeEOL ) {
+				printf ("%s", encoded EOL)
+			} else {
+				print encoded
+			}
+		}
+		END {
+			#if ( EncodeEOL ) print ""
+		}
+	'
 }
 
 gh_clone () {
-  [ $# -ne 1 ] && echo "USAGE: $0 repository" && return 1
-  local url="git@github.com:$(__gh_url_encode $(__gh_local_dir))/$(__gh_url_encode ${1}).git"
-  __gh_debug "rest-url: [$url]"
-  git clone $url
+	[ $# -ne 1 ] && echo "USAGE: $0 repository" && return 1
+	local url="git@github.com:$(__gh_url_encode $(__gh_local_dir))/$(__gh_url_encode ${1}).git"
+	__gh_debug "rest-url: [$url]"
+	git clone $url
 }
 
+
+__gh_check_for_origin() {
+	git remote -v | grep '^origin'
+}
+
+gh_import() {
+	local userid;
+	if [ $# -eq 0 ]; then
+		userid=$(__gh_parent_dir)
+	else
+		userid=$1
+	fi
+	
+	local repo=$(__gh_local_dir)
+	
+	git status 2>/dev/null
+	if [ $? -ne 0 ]; then
+		__gh_error "please use 'git init' first"
+		return -1;
+	fi 
+
+	local url="git@github.com:${userid}/${repo}.git"
+	__gh_info "importing to [$url]"
+
+	curl -u "$userid" https://api.github.com/user/repos -d '{"name":"'$repo'"}'
+
+	__gh_check_for_origin 1>&2 2>/dev/null
+	if [ $? -eq 0 ]; then
+		git remote set-url origin "$url"
+	else
+		git remote add origin "$url"
+	fi
+	
+	git push origin master
+}
+
+
 __gh_param_or_dir () {
-  local userid;
-  if [ -z "$1" ]; then
-     __gh_local_dir
-  else
-     echo "$*"
-  fi
+	local userid;
+	if [ -z "$1" ]; then
+		__gh_local_dir
+	else
+		echo "$*"
+	fi
 }
 
 __gh_fetch_and_check () {
-  __gh_debug "rest-url: [$*]"
-  local json;
-  json=$(curl -s "$*")
-  local ret=$?
-  [ $ret -ne 0 ] && return $ret
-  [ -n "$(echo \"$json\" | grep 'Not Found')" ] && return 1 || echo "$json"
+	__gh_debug "rest-url: [$*]"
+	local json;
+	json=$(curl -s "$*")
+	local ret=$?
+	[ $ret -ne 0 ] && return $ret
+	[ -n "$(echo \"$json\" | grep 'Not Found')" ] && return 1 || echo "$json"
 }
 
-
 gh_info_json () {
-  local userid=$(__gh_param_or_dir "$*")
-  __gh_fetch_and_check "https://api.github.com/users/$(__gh_url_encode ${userid})"
-  local ret=$?
-  [ $ret -ne 0 ] && __gh_error "fetching data for user [${userid}] failed" && return $ret || return 0
+	local userid=$(__gh_param_or_dir "$*")
+	__gh_fetch_and_check "https://api.github.com/users/$(__gh_url_encode ${userid})"
+	local ret=$?
+	[ $ret -ne 0 ] && __gh_error "fetching data for user [${userid}] failed" && return $ret || return 0
 }
 
 gh_repos_json () {
-  local userid=$(__gh_param_or_dir "$*")
-  __gh_fetch_and_check "https://api.github.com/users/$(__gh_url_encode ${userid})/repos"
-  local ret=$?
-  [ $ret -ne 0 ] && __gh_error "fetching repos for user [${userid}] failed" && return $ret || return 0
+	local userid=$(__gh_param_or_dir "$*")
+	__gh_fetch_and_check "https://api.github.com/users/$(__gh_url_encode ${userid})/repos"
+	local ret=$?
+	[ $ret -ne 0 ] && __gh_error "fetching repos for user [${userid}] failed" && return $ret || return 0
 }
 
 gh_repos_urls () {
-  ###############################################################
-  ## NOTE: local json=$(...) would destroy the content of $? !!!
-  ###############################################################
-  local json
-  json=$(gh_repos_json "$*")
-  local ret=$?
-  [ $ret -ne 0 ] && return $ret
-  echo "$json" | grep "ssh_url" |  awk '{print $2}' | sed -e 's/\"//g' -e 's/,//g'
+	###############################################################
+	## NOTE: local json=$(...) would destroy the content of $? !!!
+	###############################################################
+	local json
+	json=$(gh_repos_json "$*")
+	local ret=$?
+	[ $ret -ne 0 ] && return $ret
+	echo "$json" | grep "ssh_url" |  awk '{print $2}' | sed -e 's/\"//g' -e 's/,//g'
 }
 
 gh_repos () {
-  local urls
-  urls=$(gh_repos_urls "$*")
-  local ret=$?
-  [ $ret -ne 0 ] && return $ret
-  echo "$urls" | sed -e 's/.*\/\(.*\)\.git$/\1/g'
+	local urls
+	urls=$(gh_repos_urls "$*")
+	local ret=$?
+	[ $ret -ne 0 ] && return $ret
+	echo "$urls" | sed -e 's/.*\/\(.*\)\.git$/\1/g'
 }
 
 gh_backup () {
-  local urllist
-  urllist=$(gh_repos_urls "$*")
-  local ret=$?
-  [ $ret -ne 0 ] && return $ret
+	local urllist
+	urllist=$(gh_repos_urls "$*")
+	local ret=$?
+	[ $ret -ne 0 ] && return $ret
 
-  local cnt_repo=0
-  local cnt_clone=0
-  local cnt_clone_err=0
-  local cnt_pull=0
-  local cnt_pull_err=0
-  local repo_url
-  local repo
+	local cnt_repo=0
+	local cnt_clone=0
+	local cnt_clone_err=0
+	local cnt_pull=0
+	local cnt_pull_err=0
+	local repo_url
+	local repo
 
-  for repo_url in $urllist; do
-    repo=$(echo $repo_url | sed -e 's/^.*\///' -e 's/\.git$//')
-    __gh_info "processing [$repo]"
-    cnt_repo=$(expr $cnt_repo + 1)
-    if [ -d "$repo" ]; then
-      __gh_info "using 'git pull'"
-      cd $repo
-      git pull -q
-      if [ $? -ne 0 ]; then
-        __gh_warn "failed to pull repo [$repo]"
-        cnt_pull_err=$(expr $cnt_pull_err + 1)
-      else
-        cnt_pull=$(expr $cnt_pull + 1)
-      fi
-      cd ..
-    else
-      __gh_info "using 'git clone' with url [$repo_url]"
-      git clone -q $repo_url
+	for repo_url in $urllist; do
+		repo=$(echo $repo_url | sed -e 's/^.*\///' -e 's/\.git$//')
+		__gh_info "processing [$repo]"
+		cnt_repo=$(expr $cnt_repo + 1)
+		if [ -d "$repo" ]; then
+			__gh_info "using 'git pull'"
+			cd $repo
+			git pull -q
+			if [ $? -ne 0 ]; then
+				__gh_warn "failed to pull repo [$repo]"
+				cnt_pull_err=$(expr $cnt_pull_err + 1)
+			else
+				cnt_pull=$(expr $cnt_pull + 1)
+			fi
+			cd ..
+		else
+			__gh_info "using 'git clone' with url [$repo_url]"
+			git clone -q $repo_url
 
-      if [ $? -ne 0 ]; then
-        __gh_warn "failed to clone repo [$repo]"
-        cnt_clone_err=$(expr $cnt_clone_err + 1)
-      else
-        cnt_clone=$(expr $cnt_clone + 1)
-      fi
-    fi
-  done
+			if [ $? -ne 0 ]; then
+				__gh_warn "failed to clone repo [$repo]"
+				cnt_clone_err=$(expr $cnt_clone_err + 1)
+			else
+				cnt_clone=$(expr $cnt_clone + 1)
+			fi
+		fi
+	done
 
-  __gh_info "total: $cnt_repo pulled: $cnt_pull err_pulled: $cnt_pull_err cloned: $cnt_clone err_cloned: $cnt_clone_err"
+	__gh_info "total: $cnt_repo pulled: $cnt_pull err_pulled: $cnt_pull_err cloned: $cnt_clone err_cloned: $cnt_clone_err"
 
-  if [ $cnt_clone_err -ne 0 ] || [ $cnt_pull_err -ne 0 ]; then
-    __gh_warn "some repositories couldn't be cloned or pulled"
-    return 1
-  else
-    return 0
-  fi
+	if [ $cnt_clone_err -ne 0 ] || [ $cnt_pull_err -ne 0 ]; then
+		__gh_warn "some repositories couldn't be cloned or pulled"
+		return 1
+	else
+		return 0
+	fi
 }
 
 # TODO: idea 
@@ -247,42 +285,55 @@ gh_backup () {
 #
 # { echo -ne "HTTP/1.0 200 OK\r\nContent-Length: $(wc -c <some.file)\r\n\r\n"; cat some.file; } | nc -l -p 8080
 
-ght () {  
-  case "$1" in
-    "version")    echo "Github Tools v$GHTOOLS_VERSION - (c) 2015 Tom Nussbaumer <thomas.nussbaumer@gmx.net>";;
-    "help")       gh_help;;
-    "clone")      shift; gh_clone      "$@";;
-    "info")       shift; gh_info_json  "$@";;
-    "repos")      shift; gh_repos      "$@";;
-    "repos-urls") shift; gh_repos_urls "$@";;
-    "repos-json") shift; gh_repos_json "$@";;
-    "backup")     shift; gh_backup     "$@";;
-    "root")       if [ -z "$2" ]; then
-                    GHTOOLS_ROOT=""
-                    __gh_info "root unset"
-                    return 0
-                  fi
-                  if [ ! -d "$2" ]; then
-                    __gh_warn "non-existing directory [$2]"
-                    return 1
-                  fi
-                  GHTOOLS_ROOT="$2" 
-                  __gh_info "root=$GHTOOLS_ROOT";;
-    "go")         if [ -n "$GHTOOLS_ROOT" ]; then
-                    if [ -d "$GHTOOLS_ROOT/$2" ]; then
-                      cd "$GHTOOLS_ROOT/$2"
-                    else
-                      __gh_warn "non-existing directory [$GHTOOLS_ROOT/$2]"
-                      return 1
-                    fi
-                  else  
-                    __gh_warn "no root set. use 'ght root' to set a root."
-                    return 1
-                  fi
-                  ;;
-    "debug")      GHTOOLS_DEBUG="$2"
-                  [ -z "$GHTOOLS_DEBUG" ] && __gh_info "debug=off" || __gh_info "debug=on";;
-    *)            gh_help;;
-  esac
+ght () {
+	case "$1" in
+		"version")
+			echo "Github Tools v$GHTOOLS_VERSION - (c) 2015 Tom Nussbaumer <thomas.nussbaumer@gmx.net>";;
+		"help")
+			gh_help;;
+		"clone")
+			shift; gh_clone      "$@";;
+		"info")
+			shift; gh_info_json  "$@";;
+		"repos")
+			shift; gh_repos      "$@";;
+		"import")
+			shift; gh_import     "$@";;
+		"repos-urls")
+			shift; gh_repos_urls "$@";;
+		"repos-json")
+			shift; gh_repos_json "$@";;
+		"backup")
+			shift; gh_backup     "$@";;
+		"root")
+			if [ -z "$2" ]; then
+				GHTOOLS_ROOT=""
+				__gh_info "root unset"
+				return 0
+			fi
+			if [ ! -d "$2" ]; then
+				__gh_warn "non-existing directory [$2]"
+				return 1
+			fi
+			GHTOOLS_ROOT="$2" 
+			__gh_info "root=$GHTOOLS_ROOT";;
+		"go")
+			if [ -n "$GHTOOLS_ROOT" ]; then
+				if [ -d "$GHTOOLS_ROOT/$2" ]; then
+					cd "$GHTOOLS_ROOT/$2"
+				else
+					__gh_warn "non-existing directory [$GHTOOLS_ROOT/$2]"
+					return 1
+				fi
+			else
+				__gh_warn "no root set. use 'ght root' to set a root."
+				return 1
+			fi;;
+		"debug")
+			GHTOOLS_DEBUG="$2"
+			[ -z "$GHTOOLS_DEBUG" ] && __gh_info "debug=off" || __gh_info "debug=on";;
+		*)
+			gh_help;;
+	esac
 }
 
